### ISSUE TITLE
javascript.suggest.includeAutomaticOptionalChainCompletions isn't working

### ISSUE THREAD

**Issue by Sehun-Kiim** [Issue-Labeling-Bot/Labeling_Bot#100]
This happens in current Insiders 1.41.0

VSCode Version: Insiders 1.41.0
OS Version: macOS 10.15.1
Steps to Reproduce:

Set "javascript.suggest.includeAutomaticOptionalChainCompletions": false,
Set "typescript.suggest.includeAutomaticOptionalChainCompletions": false,
Copy the following to a JS and a TS file:
const adventurer = {
    name: 'Alice',
    cat: {
        name: 'Dinah'
    }
};

const dogName = adventurer
Write ?. in front of const dogName = adventurer and notice that automatic optional chain completions are still triggered.
Note: In VS Code v1.40.1 changing both settings to true doesn't trigger the completion.

Does this issue occur when all extensions are disabled? Yes

**Comment by Choi-kwang-hyun** [comment]
bug : 0.3775506913661957

**Comment by Choi-kwang-hyun** [comment]
verified : 0.3629792034626007
