### ISSUE TITLE
No more dummy in config file

### ISSUE THREAD

**Issue by minseonsim** [Issue-Labeling-Bot/Labeling_Bot#102]
This PR does not intend to fix any defect. It is internal to notepad++ that writing/updating the config should be uniform across.

Example: "Document map", "Function List", "Folder as Workspace" etc. writes plugin name as "Notepad++::InternalFunction" for their docking window, then why not "Find result"?

**Comment by Choi-kwang-hyun** [comment]
verified : 0.3998216390609741

**Comment by Choi-kwang-hyun** [comment]
bug : 0.320831298828125
