### ISSUE TITLE
Markdown: Find widget arrows look disabled

### ISSUE THREAD

**Issue by Sehun-Kiim** [Issue-Labeling-Bot/Labeling_Bot#103]
Issue Type: Bug

Open markdown preview
Ctrl+F Search for existing term
There are matches but the arrows look faded
Screenshot (75)

VS Code version: Code - Insiders 1.39.0-insider (55825e9, 2019-09-10T05:25:22.729Z)
OS version: Windows_NT x64 10.0.18362

**Comment by Choi-kwang-hyun** [comment]
bug : 0.4843900501728058

**Comment by Choi-kwang-hyun** [comment]
verified : 0.46102678775787354
