### ISSUE TITLE
Accessibility: tabbing in an opened combobox sends the cursor to the first item in the document instead of next

### ISSUE THREAD

**Issue by Sehun-Kiim** [Issue-Labeling-Bot/Labeling_Bot#104]
Environment Details:
Date: 2019-08-09T07:49:00.254Z
VS Code 1.37.0
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

Open VS Code Settings, find a combobox (dropdown) and tab until it's focused.
Press spacebar or enter to open the dropdown.
Press Tab
Expected:
Combobox closes, focus moves to the next item in the tab hierarchy

Actual:
Focus moves to the first item in the UI (menus), I must tab all the way back to where I was.

Impact: accessibility/keyboard users

**Comment by Choi-kwang-hyun** [comment]
verified : 0.38492217659950256

**Comment by Choi-kwang-hyun** [comment]
bug : 0.3276783227920532
