### ISSUE TITLE
Improve space usage in File Association dialog

### ISSUE THREAD

**Issue by minseonsim** [Issue-Labeling-Bot/Labeling_Bot#108]
This improves the commit 77e8164 that didn't completely fix #535.
This fixes the remaining text cuts, while adding space for future changes.
Custom extension input field has same width of extensions area.
Round numbers for object position/sizes.
"exts :" -> "extensions:" for clarification.
Add missing WS_HSCROLL, even though it seems not have effect.

**Comment by Choi-kwang-hyun** [comment]
verified : 0.4532718360424042

**Comment by Choi-kwang-hyun** [comment]
bug : 0.38492217659950256
