### ISSUE TITLE
Settings: Utilize Button for all 'Edit settings.json' link

### ISSUE THREAD

**Issue by Sehun-Kiim** [Issue-Labeling-Bot/Labeling_Bot#109]
While keyboarding through the settings I think it might look better to utilize a button instead of a link.
The Link sort of dangles a bit. Additionally there are two functional issues:

The link gets read with the extra hyperlink baggage
Separately , for any of these non-typical input elements , having the User Land on a button which also uses described by will be more obvious for accessibility users.
For elements like 'Files Exclude' , starting on the Add button would also be a little bit more obvious than the link in the description.
image

**Comment by Choi-kwang-hyun** [comment]
verified : 0.3998216390609741

**Comment by Choi-kwang-hyun** [comment]
featurerequest : 0.3276783227920532
