### ISSUE TITLE
Unable to use shortcut to close panel when terminal is focused.

### ISSUE THREAD

**Issue by Sehun-Kiim** [Issue-Labeling-Bot/Labeling_Bot#11]
VSCode: 1.50.1
OS: Kubuntu 20.04

I have a set of key mappings that allow me to use escape to close the bottom panel.

These keymappings work in all cases, except for when the terminal is in focus in the bottom panel. For example, if the Problems tab is the tab in focus in the bottom panel, hitting escape key will successfully close the terminal. If the terminal tab is selected, nothing will happen.

I have added the following lines to my user settings to make sure the command does not get eaten by the terminal...

 "terminal.integrated.commandsToSkipShell": [
        "workbench.action.closePanel"
   ],
Here are the relevant keyboard shortcuts...

    { "key": "escape", "command": "workbench.action.terminal.toggleTerminal", "when": "activePanel == 'workbench.panel.terminal'" },// this one doesn't work
    { "key": "escape", "command": "workbench.action.closePanel", "when": "activePanel == 'workbench.panel.terminal'" },//and this one doesnt work
    { "key": "escape", "command": "workbench.action.closePanel", "when": "activePanel == 'workbench.panel.markers'" },
    { "key": "escape", "command": "workbench.action.closePanel", "when": "activePanel == 'workbench.panel.output'" },
    { "key": "escape", "command": "workbench.action.closePanel", "when": "activePanel == 'workbench.panel.repl'" },
    { "key": "escape", "command": "workbench.action.closePanel", "when": "activePanel == 'workbench.panel.comments'" },

**Comment by Choi-kwang-hyun** [comment]
needsmoreinfo : 0.15611489117145538

**Comment by Choi-kwang-hyun** [comment]
debt : 0.04743587225675583

**Comment by Choi-kwang-hyun** [comment]
duplicate : 0.01972912810742855
