### ISSUE TITLE
[html][css] [custom data] Custom data settings: User level setting

### ISSUE THREAD

**Issue by Sehun-Kiim** [Issue-Labeling-Bot/Labeling_Bot#111]
Testing #79843

no indication that the setting can only be in the workspace settings
html custom description mentions it (css does not), but that's very hidden
-> I suggest to also allow if for user settings
no indication if path needs to be relate, absolute or URI
no indication that reload is needed

**Comment by Choi-kwang-hyun** [comment]
verified : 0.5544804334640503

**Comment by Choi-kwang-hyun** [comment]
bug : 0.40734341740608215
