### ISSUE TITLE
VS Code was lost on shutdown with pending update

### ISSUE THREAD

**Issue by Sehun-Kiim** [Issue-Labeling-Bot/Labeling_Bot#114]
It was the second time ,it happend.
I download VScode's update patch when I was coding , and then shut down the computer and forgot to update it.
Next day I turn the computer on and can't find VScode anywhere , all the file was empty.

OS Version : Windows 10 Home

**Comment by Choi-kwang-hyun** [comment]
needsmoreinfo : 0.6224693655967712
