### ISSUE TITLE
Process Explorer: "CPU %" column french name is too long: "% PROCESSEUR"

### ISSUE THREAD

**Issue by Sehun-Kiim** [Issue-Labeling-Bot/Labeling_Bot#116]
Issue Type: Bug

The column name for CPU in French is too long and overlaps on the second column (Memory): currently it's "% PROCESSEUR".

I suggest replacing the string with the French translation used in Windows task manager:

% UC

"UC" is the standard French abbreviation for "CPU" according to CSA and CEI. See the Canadian Government's linguistic data bank on term "CPU".

VS Code version: Code 1.23.0 (7c7da59, 2018-05-03T16:44:55.614Z)
OS version: Windows_NT x64 6.1.7601

**Comment by Choi-kwang-hyun** [comment]
verified : 0.46102678775787354

**Comment by Choi-kwang-hyun** [comment]
bug : 0.44553956389427185
