### ISSUE TITLE
Web: Webview is stealing keybindings 

### ISSUE THREAD

**Issue by Sehun-Kiim** [Issue-Labeling-Bot/Labeling_Bot#117]
Linux, chrome

Open a markdown file preview
Press F1 > expect to get the quick open list, instead Chrome help gets opened 🐛
The issue it seems is that while the web view is opened it steals all keybindings from vscode. Even if chrome is in full screen.
Adding important since I think we should tackle this if possible, otherwise it would lead to a lot of unexpected ctrl + w closing whole vscode behavior.

@rebornix reply:

It's a really good catch, even though we don't know the answer to it with current implementation. The iframe is running in another domain where keyboard.lock is not allowed at this moment WICG/keyboard-lock#40

**Comment by Choi-kwang-hyun** [comment]
verified : 0.4225146472454071

**Comment by Choi-kwang-hyun** [comment]
bug : 0.3629792034626007
