### ISSUE TITLE
Terminal link detection issues

### ISSUE THREAD

**Issue by Sehun-Kiim** [Issue-Labeling-Bot/Labeling_Bot#119]
Testing #21021

linkComputer.test.ts contains a set of tests used for editor link detection. Some links that do not get fully detected in the terminal. Some do get detected, but partially or contain trailing periods, etc:

// Click here to learn more. https://go.microsoft.com/fwlink/?LinkID=513275&clcid=0x409
// Click here to learn more. https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).
aspx

For instructions, see https://go.microsoft.com/fwlink/?LinkId=166007.</value>
For instructions, see https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx.</
value>
x = "https://en.wikipedia.org/wiki/Zürich";
請參閱 http://go.microsoft.com/fwlink/?LinkId=761051。
x = "file:///foo.bar";
x = "file://c:/foo.bar";
x = "file://shäres/foo.bar";
Some text, then http://www.bing.com.

**Comment by Choi-kwang-hyun** [comment]
verified : 0.4378334879875183

**Comment by Choi-kwang-hyun** [comment]
bug : 0.41490885615348816
