### ISSUE TITLE
Closing VS Code with pending update reopens vs code after update

### ISSUE THREAD

**Issue by Sehun-Kiim** [Issue-Labeling-Bot/Labeling_Bot#121]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: Bug

I'm not 100% sure on how to reproduce, however, this is what I observed:
I had VS Code open. I closed it by hitting the X button. I saw a small message box show up after vs code closed with something along the lines of Updating VS Code and it had a progress bar. The popup w/ progress bar finished and closed. VS Code was relaunched automagically.

Expected behaviour: VS Code closes (exits)

VS Code version: Code 1.41.1 (26076a4, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17763

System Info
Extensions (4)

**Comment by Choi-kwang-hyun** [comment]
needsmoreinfo : 0.3923468291759491
