### ISSUE TITLE
[themes] IconTheme doesn't work with spaces in names

### ISSUE THREAD

**Issue by Sehun-Kiim** [Issue-Labeling-Bot/Labeling_Bot#122]
Issue Type: Bug

have a file or folder that contains a space in its name, for ex 'Some stuff' folder
set up a custom icon theme and include a specific icon for folder/file of that name, for ex. :
"folderNames": {
        "Some stuff": "_special_icon"
    }

Result: icon is not applied to the 'Some stuff' folder.
Expected it to apply.

VS Code version: Code - Insiders 1.41.0-insider (7f1975a, 2019-12-04T10:20:42.228Z)
OS version: Windows_NT x64 10.0.17763

**Comment by Choi-kwang-hyun** [comment]
verified : 0.348655104637146

**Comment by Choi-kwang-hyun** [comment]
bug : 0.3007555902004242
