### ISSUE TITLE
Add breakpoint inside Search editor view

### ISSUE THREAD

**Issue by Sehun-Kiim** [Issue-Labeling-Bot/Labeling_Bot#42]
When you search code with the command search editor: new search editor and display results. It is possible on the left of number line (for each files):

to add breakpoint (this breakpoint will be applied to the real file position)
to show existing breakpoint

**Comment by Choi-kwang-hyun** [comment]
featurerequest : 0.3998216390609741

**Comment by Choi-kwang-hyun** [comment]
verified : 0.3557848632335663
