### ISSUE TITLE
Terminal closes automatically with the msg: terminated with exit code 3221225477

### ISSUE THREAD

**Issue by Sehun-Kiim** [Issue-Labeling-Bot/Labeling_Bot#43]
VSCode Version: 1.51.1 (user setup)
OS Version: Windows_NT x64 10.0.18363
Commit: e5a624b
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
Steps to Reproduce:
Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Choi-kwang-hyun** [comment]
needsmoreinfo : 0.320831298828125
