### ISSUE TITLE
Enable select json block in terminal with double click

### ISSUE THREAD

**Issue by Sehun-Kiim** [Issue-Labeling-Bot/Labeling_Bot#44]
Issue Type: Feature Request

Request the feature which is similar to iterm2 JSON block select. i.e. When double click "{" or "}" in terminal window, it will automatically select the whole JSON block

VS Code version: Code 1.51.1 (e5a624b, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 19.6.0

**Comment by Choi-kwang-hyun** [comment]
duplicate : 0.3140605390071869
