### ISSUE TITLE
Redo last keyboard shortcut

### ISSUE THREAD

**Issue by Sehun-Kiim** [Issue-Labeling-Bot/Labeling_Bot#47]
It would be nice if VSCode could allow users to redo the last the last keyboard shortcut with a keyboard shortcut, even if there is nothing undone.

That might sound weird at first, but considering some actions sometimes need multiple keyboard shortcuts to be run one after the other, this would be very useful to repeat them, without needing to re-enter all those shortcuts again.

For example, in Microsoft Word, you can:

select some text
make the selected text bold (ctrl+b)
undo the last action (ctrl+z)
selected text is now normal again
redo the last action (ctrl+y)
selected text is now bold again
select some other text (2nd selected text)
redo the same action, even if there is nothing to "redo" (ctrl+y too)
2nd selected text is now bold too now
It's basically a "redo even if nothing to redo".

An example of a use case in VSCode would be:

select a block of code
enter the keyboard shortcut to toggle block comment (shift+alt+a)
selected block is now a comment
select another block of code
enter the keyboard shortcut to redo the last action (ctrl+y)
selected block is now a comment too
...
repeat "redo" keyboard shortcut to apply

**Comment by Choi-kwang-hyun** [comment]
featurerequest : 0.348655104637146
