### ISSUE TITLE
Support settind standard input for debugging

### ISSUE THREAD

**Issue by Sehun-Kiim** [Issue-Labeling-Bot/Labeling_Bot#48]
I'd like a feature like at ideone.com whereby standard input can be set and reused non-interactively whenever the code is run. Currently I work around it by creating a file and reading from it instead. But it requires very different code which is a disadvantage particularly when the finished programme is supposed to operate on standard input.

**Comment by Choi-kwang-hyun** [comment]
featurerequest : 0.4225146472454071
