### ISSUE TITLE
[Feature Request] Sort lines randomly (i.e., shuffle lines)

### ISSUE THREAD

**Issue by Sehun-Kiim** [Issue-Labeling-Bot/Labeling_Bot#52]
In Notepad++ 7.8.9, current as of this writing, there is an ability to sort lines in a variety of ways, but no choice to sort the lines randomly, that is, to shuffle them. It would be nice to have this as a choice in addition to the existing sort types.

**Comment by Choi-kwang-hyun** [comment]
featurerequest : 0.6926519870758057
