### ISSUE TITLE
How to get the cmd exit code run by terminal.sendText?

### ISSUE THREAD

**Issue by Sehun-Kiim** [Issue-Labeling-Bot/Labeling_Bot#55]
According to #97217 , the exitStatus can get the terminal status only when the terminal exit. But how can i get the cmd exit code after running in a vscode terminal? I know it may be difficult by tracing the stdout and stderr and they are not implemented. But if there any way to get the cmd exit code only please?

Like follows, could i get the exit code of cmd without kill the terminal please? Thanks a lot.

const cmd = "ls -al ";
this._terminal.sendText(cmd);
this._terminal.show();

**Comment by Choi-kwang-hyun** [comment]
integratedterminal : 0.30736804008483887
