### ISSUE TITLE
[Feature request] Add new plugins API messages for getting/releasing Scintilla indicator number

### ISSUE THREAD

**Issue by Sehun-Kiim** [Issue-Labeling-Bot/Labeling_Bot#58]
Description of the Issue
There are currently several plugins that use Scintilla indicators but there is no way for a plugin to know which indicator number is already used by another plugin so an unwanted plugins "cross-talk" happens as they track indicators placed by another plugin.

To name several plugins using indicators - DSpellCheck, DoxyIt, Compare

Steps to Reproduce the Issue
It appears that Compare v2.0 and DoxyIt plugins currently use the same indicator number.

Install both plugins.
Compare two files that have several lines differing by just one word (so you have changed lines, not only added/removed)
Press TAB key (DoxyIt shortcut for visiting function description fields)
DoxyIt will visit the Compare changed highlight indicators as well because the Compare's indicator number is the same as DoxyIt's.

This is just an example of the problem. It might appear in the future in different forms depending on the plugins.

Suggestion
Add new NPPM_GET_SCINT_INDICATOR and NPPM_FREE_SCINT_INDICATOR plugin API messages so each plugin gets a different indicator number.
Of course Notepad++ should keep a list of the free indicator numbers.

**Comment by Choi-kwang-hyun** [comment]
featurerequest : 0.33459946513175964
