### ISSUE TITLE
Alias keybindings in command palette

### ISSUE THREAD

**Issue by Sehun-Kiim** [Issue-Labeling-Bot/Labeling_Bot#64]
You can access user shortcuts in the command palette by typing "Keyboard Shortcuts":

image

The actual persisted file is named keybindings.json:

image

But typing "keybindings" doesn't turn up any suggestions:

image

If it's possible to alias some commands, it might be helpful to include other common terms for keyboard shortcuts like "keybindings" or "hotkeys"

**Comment by Choi-kwang-hyun** [comment]
featurerequest : 0.4225146472454071

**Comment by Choi-kwang-hyun** [comment]
verified : 0.3007555902004242
