### ISSUE TITLE
Allow to split editor vertically via context menu

### ISSUE THREAD

**Issue by Sehun-Kiim** [Issue-Labeling-Bot/Labeling_Bot#69]
VSCode Version: Code 1.13.1 (379d2ef, 2017-06-14T18:21:47.485Z)
OS Version: Windows_NT ia32 10.0.15063
it took me a while today to realise the reason I couldn't get 'side-by-side' file views was because the 'editor group layout' was set to vertically stacked. To be fair the 'split editor' icon does change according to which mode you're in but it's a bit subtle. Why not provide a right-click context menu on the 'split editor' button to allow a switch?

**Comment by Choi-kwang-hyun** [comment]
featurerequest : 0.3702353835105896

**Comment by Choi-kwang-hyun** [comment]
verified : 0.3276783227920532
