### ISSUE TITLE
automatically place a semicolon after writing a parenthesis instead of inside

### ISSUE THREAD

**Issue by Sehun-Kiim** [Issue-Labeling-Bot/Labeling_Bot#71]
When typing an open parenthesis followed by a semicolon to close the line, it actually types "(;)"

Isnt it better in terms of productivity to automatically place the semicolon after the parenthesis like "();" ? it avoids the user to have to press the right key to move the cursor out of the parenthesis

**Comment by Choi-kwang-hyun** [comment]
featurerequest : 0.3415925204753876
