### ISSUE TITLE
Editors show generic icon until they are loaded

### ISSUE THREAD

**Issue by Sehun-Kiim** [Issue-Labeling-Bot/Labeling_Bot#72]
Version: 1.42.0 (user setup)
Commit: ae08d54
Date: 2020-02-06T10:51:34.058Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

Create two new untitled editors
Switch one of them to a language mode with a non-default icon (such as C#)
Bring the other editor into focus
Close and restart VS Code
Expected : Icons show correctly for the specified language

Actual : Icon is default editor icon until the editor is selected

**Comment by Choi-kwang-hyun** [comment]
verified : 0.41490885615348816

**Comment by Choi-kwang-hyun** [comment]
bug : 0.348655104637146
