### ISSUE TITLE
Errors on fields with URI format not reported in Settings UI

### ISSUE THREAD

**Issue by Sehun-Kiim** [Issue-Labeling-Bot/Labeling_Bot#77]
Found this issue while trying to set java.format.settings.url's format to uri (or uri-reference), in order to fix redhat-developer/vscode-java#1237

VSCode Version: 1.42.0-insider (7e64866)
OS Version: Mac OS 10.14.6
Steps to Reproduce:

Have a "mysetting" setting define "format":"uri" (as documented in https://code.visualstudio.com/api/references/contribution-points#contributes.configuration)
Open settings in UI, write then delete some value, no error is shown
Open settings.json, see that "mysetting":"" has a warning: String is not a URI: URI expected.
Screen Shot 2020-01-15 at 7 44 33 PM

The validation error should be displayed in the UI too (as it does when using a validation pattern)

Does this issue occur when all extensions are disabled?: Maybe

**Comment by Choi-kwang-hyun** [comment]
verified : 0.4301573634147644

**Comment by Choi-kwang-hyun** [comment]
bug : 0.4301573634147644
