### ISSUE TITLE
Padding for tab captions in find-and-replace dialog

### ISSUE THREAD

**Issue by minseonsim** [Issue-Labeling-Bot/Labeling_Bot#78]
Hello,

in my opinion a little padding is appropriate for the tab captions in the find-and-replace dialog. Take a look at the padding of the buttons on the same dialog. This looks a little bit better and provides more space for a tab to get clicked.

**Comment by Choi-kwang-hyun** [comment]
verified : 0.6370407938957214

**Comment by Choi-kwang-hyun** [comment]
bug : 0.5544804334640503
