### ISSUE TITLE
Named find-and-replace pairs

### ISSUE THREAD

**Issue by minseonsim** [Issue-Labeling-Bot/Labeling_Bot#80]
Please enable to save the text of the find and replace textboxes of the find-and-replace dialog as named pairs that you can view and select again at a later time. The options of check boxes and radio buttons should also be saved for a named pair. (A pair would be usable for find-only, too.)

This feature would make Notepad++ much more useful with regard to developing a chain of regular expressions that you have to apply, especially in combination with this feature: issue # 563.

**Comment by Choi-kwang-hyun** [comment]
featurerequest : 0.46102678775787354
