### ISSUE TITLE
64 bit version is not registering itself in "Open with" menu

### ISSUE THREAD

**Issue by minseonsim** [Issue-Labeling-Bot/Labeling_Bot#81]
Description of the Issue
Notepad++ 64-bit version's icon is not showing when using "Open with" context menu.

Steps to Reproduce the Issue
Right click on any file and go to Open With
Choose default program -> This opens new dialog with suggested applications
Browse for Notepad++ and select notepad++.exe.
The dialog still doesn't show notepad++ and you can't open a file with notepad++.
Expected Behaviour
The complete process should show notepad++ icon and users should be able to open any file with app.

Actual Behaviour
Not able to open any file with notepad++

**Comment by Choi-kwang-hyun** [comment]
verified : 0.33459946513175964

**Comment by Choi-kwang-hyun** [comment]
bug : 0.33459946513175964
