### ISSUE TITLE
Terminal's selection is wrong visually after resizing terminal

### ISSUE THREAD

**Issue by Sehun-Kiim** [Issue-Labeling-Bot/Labeling_Bot#82]
VSCode Version: 1.42.1
OS Version: macOS 10.14.4 (18E2034)
Steps to Reproduce:

select text to the end of line
reduce width of terminal
Screen Shot 2020-02-18 at 7 03 22 PM
Screen Shot 2020-02-18 at 7 03 29 PM

**Comment by Choi-kwang-hyun** [comment]
bug : 0.3923468291759491

**Comment by Choi-kwang-hyun** [comment]
integratedterminal : 0.3775506913661957
