### ISSUE TITLE
Auto-insertion of apices too aggressive

### ISSUE THREAD

**Issue by minseonsim** [Issue-Labeling-Bot/Labeling_Bot#83]
When I'm editing code and I decide to add double apices (for example) before and after a word, the auto-insertion inserts them in couples, so that I end up deleting the second insertion.
It would be better maybe to insert double-double apices (or the others) only once if the cursor has non-space text directly on its right or its left.

**Comment by Choi-kwang-hyun** [comment]
featurerequest : 0.3140605390071869
