### ISSUE TITLE
Search Editor peek say "Definitions ()"

### ISSUE THREAD

**Issue by Sehun-Kiim** [Issue-Labeling-Bot/Labeling_Bot#84]
VSCode Version: 1.43 Insiders
OS Version: Windows 10
Found while testing #91331

Steps to Reproduce:

Open the vscode-docs repo and create an empty Search Editor
Search for "VSCode" and set Match Case and Match Whole Word
Double-click on a file path to open the Peek view.
Title bar says "Definitions ()" with the count. I would have expected the text to say "Matches ()"

image

**Comment by Choi-kwang-hyun** [comment]
verified : 0.33459946513175964

**Comment by Choi-kwang-hyun** [comment]
bug : 0.3140605390071869
