### ISSUE TITLE
Application locks up when network folder unreachable

### ISSUE THREAD

**Issue by minseonsim** [Issue-Labeling-Bot/Labeling_Bot#86]
I am editing files on a remote Windows share, and occasionally this share is disconnected. If Notepad++ loses and regains focus while the share is disconnected, it completely locks up for about 30 seconds while it tries to check for file modifications.

Potential fixes:

Make the timeout shorter
Check for file modifications in a separate thread

**Comment by Choi-kwang-hyun** [comment]
verified : 0.3007555902004242
