### ISSUE TITLE
Debug start view: Not shown after deleting launch.json

### ISSUE THREAD

**Issue by Sehun-Kiim** [Issue-Labeling-Bot/Labeling_Bot#89]
Testing #91143

Open a new folder that doesn't have a launch.json
Go to the debug view and use the "create a launch.json file" command from there
Delete the generated .vscode folder that has the new launch.json file
I expected at this point that the view would revert back to the start view. Instead, it allows me to start running, which of course results in "Configuration 'Launch Program' is missing in 'launch.json'.", and then reverts back the start view:
Screen Shot 2020-02-25 at 3 33 26 PM

(#91426)

**Comment by Choi-kwang-hyun** [comment]
debug : 0.5156299471855164

**Comment by Choi-kwang-hyun** [comment]
verified : 0.41490885615348816
