### ISSUE TITLE
Disable drag-and-drop text editing (NPP v6.3 and v6.6.9)

### ISSUE THREAD

**Issue by minseonsim** [Issue-Labeling-Bot/Labeling_Bot#90]
Description of the Issue
In many text editors, you can drag-and-drop text from one place in the document to another. Some user may like the feature, others (such as myself) do not and wish the feature could be disabled. Unfortunately, there does not appear to be any way to do this.

Steps to Reproduce the Issue
Open any text file
Select some text, click and drag, then release the mouse
The text is cut from the original and pasted to the new location
Expected Behavior
The ability to turn this feature off (in Settings > Preferences)

Actual Behavior
NA

Debug Information
NA

**Comment by Choi-kwang-hyun** [comment]
featurerequest : 0.30736804008483887
