### ISSUE TITLE
Fix scintilla restoring wrapped buffer issue

### ISSUE THREAD

**Issue by minseonsim** [Issue-Labeling-Bot/Labeling_Bot#91]
If you switch between tabs while wrap mode is enable, text jump to another lines.
It's an old bug, fixed in v7.5.9, but it had performance regression so it was reverted in v6.0.0.

It's been one year, and I'm back.
This works whatever the size of the file.
There isn't any performance regression because we don't use SCI_ENSUREVISIBLE scintilla command.

In case wrap option on, The restore position function is done in twice steps.

First step: set selection, set anchor, set xoffset...
Second step: once Scintilla has send the notification SCN_PAINTED, we can scroll several lines to set the first visible line to the correct wrapped line.
Keep in mind that Line wrapping is a background activity that takes time, specially for huge file.

**Comment by Choi-kwang-hyun** [comment]
verified : 0.348655104637146

**Comment by Choi-kwang-hyun** [comment]
bug : 0.3007555902004242
