### ISSUE TITLE
Editor limit: running "Save As" will close one editor when limit reached

### ISSUE THREAD

**Issue by Sehun-Kiim** [Issue-Labeling-Bot/Labeling_Bot#92]
Steps to Reproduce:

configure a workbench.editor.limit
open editors until limit is reached
run "Save As" on a file or untitled
=> 🐛 one editor closes

This is tricky to fix without hacks. We eventually call EditorGroupView#replaceEditors() where in the end we first open the newly saved editor and then close the old one. The reason we first open the new one and then close the old one is to preserve history. Otherwise we would close the old one, reveal the next and thus change history.

A possible fix is to have a way in editor group view to close an editor without activating the next, though that needs to be done with care in case opening fails for some reason.

**Comment by Choi-kwang-hyun** [comment]
verified : 0.5312193632125854

**Comment by Choi-kwang-hyun** [comment]
bug : 0.4301573634147644
