### ISSUE TITLE
Added new Option: Enable scrolling beyond last line

### ISSUE THREAD

**Issue by minseonsim** [Issue-Labeling-Bot/Labeling_Bot#93]
This option configures the vertical scroll range of Scintilla.
Disable this will configure the scroll range to end at last line (DEFAULT).
Enable this will configure the scroll range to end one page beyond the last line.

**Comment by Choi-kwang-hyun** [comment]
featurerequest : 0.59267657995224

**Comment by Choi-kwang-hyun** [comment]
verified : 0.5000100135803223
