### ISSUE TITLE
Update old themes to use the correct style IDs for Pascal

### ISSUE THREAD

**Issue by minseonsim** [Issue-Labeling-Bot/Labeling_Bot#95]
Scintilla got a new Pascal lexer in version 1.78, which was included in Notepad++ version 5.4.4. However, this lexer also introduced new style IDs and most of Notepad++'s bundled themes that were created before version 5.4.4 haven't been updated in all that time.

This probably fixes what #249 was referring to.

**Comment by Choi-kwang-hyun** [comment]
verified : 0.3629792034626007
