### ISSUE TITLE
Minor performance enhancements

### ISSUE THREAD

**Issue by minseonsim** [Issue-Labeling-Bot/Labeling_Bot#96]
A few minor performance enhancements. Again, it is difficult to create an issue for this so hopefully this can be discussed here. Some comments about each commit:

00237d9 Scintilla can automatically handle some folding. Notepad++ can take advantage of some of it using SCI_SETAUTOMATICFOLD
d0a2bad Fairly straight forward. Use SCI_SETTARGETRANGE where possible instead of manually setting the start and end separately.
083bf48 Some enhancements while compiling the auto completion list. I will make some comments inline to better describe them.

**Comment by Choi-kwang-hyun** [comment]
featurerequest : 0.3007555902004242
